### ISSUE TITLE
Event status questions

### ISSUE THREAD

**Issue by Julian-tib** [TIBHannover/ConfIDent_schema#9]
Question regarding: https://tibhannover.github.io/ConfIDent_schema/EventStatus/

What is the difference between a delayed and a postponed event status?

What does the "planned" Event Status mean? Is this used when no date has been specified yet? Would this even be usable in our framework, since Start date is a mandatory property?

Will the original Start and End date be archived when the status is switched to delayed or postponed? Maybe this is not necessary. I don't know who should benefit from this kind of information.

**Comment by StroemPhi** [comment]
WRT the diff between `delayed` and `postponed`, I agree and see also no difference, thus removed in [1f646ff](https://github.com/TIBHannover/ConfIDent_schema/pull/11/commits/1f646ffe0d7db610bac0008f3b5d22afa1f8b26f) for now. If we remember why we had it in the schema in the first place, we need to make a ew issue.

Same goes for the diff between `as scheduled` and `planned`, thus `planned` are also dropped for now in 1f646ff. I think the idea was to have it as sort of indicator that an event in ConfIDent has a draft status, thus no DOI can be minted but only reserved yet and the organizer/curator can resume to input this info later. But this need to be though out at a different stage. Will open a seperate issue for this.

**Comment by StroemPhi** [comment]
Issue has been reopened because the need for the Event Status "planned" is now clear again, although it should be renamed to "to be confirmed" in order to indicate that a specified start and end date of an event is not yet officially decided upon. 

Use case: an event is announced with "will be happening some time this June" or "will be happening 20th June 2022 (TBC)" --> Event Start and Event End will only be a YYYY or MM-YYYY value and the corresponding Event Status will be set to "to be confirmed"
